### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by AndreaG5** [parseq/convector#3]
Hi,
I am really struggling with convector. I try to launch pipeline.py but results me in some errors so I tried a step by step procedure. I have a folder of BAM files and a .bed file correctly formatted.
I launched, as suggested in manual, at first:
> ./chimeric_solver.py -d ./data/cntrl_BAM/ -b /home/user/file.bed -r out_name_cntrl.xls --conv

After it, correctly run, I launched the second step of the pipeline, i.e. QC:
> ./qc.py /home/user/file.bed ./result/out_name_cntrl.xls ./result/out_name_test.xls 0.8

The error comes at this point:
output:

Traceback (most recent call last):
  File "./qc.py", line 292, in <module>
    main()
  File "./qc.py", line 265, in main
    normal_or_not, avtc_residuals_for_amplicons = diagnose_chromosome_ellipsoid(samples_to_test, ellipsoid, list_of_amplicons_to_test, qChisq, num_of_accepted)
  File "./qc.py", line 137, in diagnose_chromosome_ellipsoid
    dist = (distance_to_mean ** 2) / (ellipsoid[ampl][1])
ZeroDivisionError: float division by zero

I don't get what the error is. I tried looking at .xls files and I am wondering if it's some coverage value = 0 (in few amplicons, few samples) the problem or if something else.
So I decide to open up the python script and try to launch it line by line, but suddenly a realized there's an object i.e. "clean_chromosomes_amplicons" that is never defined within the script. Furthermore there're problems with "xrange" that I correct using "range" (probably depending on python version) and there're issues with "itertools()" since python told me that there is NO method itertools for defaultdict objects. 

I know that coding line by line isn't so worthy but I wanted to understand where the problem was and what I could do to overcome, since if it's a problem of coverages I don't think can be useful.

I appreciate every response, hope to solve the issue!

Specific:
1)OS: Ubuntu 20.04
2) python version 3.9.5
3)samtools 1.10

**Comment by GermanDemidov** [comment]
Hi Andrea,

nice to see that someone still uses this tool =) could you install python2? I think the scripts were written in python2. Then you'll need to use the original script with xrange, etc. 

If it does not fit you, in a meanwhile you may check the new tool for CNV detection

https://github.com/imgag/ClinCNV 

it is less specialised and requires large panels sequenced but it is regularly updated.
